import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowRight, Coins, Split, Layers, Sparkles, Clock, Info, Activity } from 'lucide-react';
import { TokenState } from './types';
import stEthImg from './images.png';
import Image from 'next/image';

// Placeholder AI explanation function - can be replaced with actual AI integration
async function explainPendleConcept(topic: string, context: string): Promise<string> {
    const explanations: Record<string, string> = {
        'Underlying': 'The underlying asset (like stETH) generates yield over time. By tokenizing it through Pendle, you can trade the future yield separately from the principal.',
        'SY': 'Standardized Yield (SY) is a wrapper that makes yield-bearing assets compatible with Pendle. It standardizes how yield accrues, enabling the protocol to split it into PT and YT.',
        'PT': 'Principal Tokens (PT) represent your claim to the underlying asset at maturity. They trade at a discount and converge to 1:1 with the underlying at expiry, providing a fixed yield.',
        'YT': 'Yield Tokens (YT) give you the right to all yield generated by the underlying until maturity. Their value decreases as maturity approaches (time decay).',
    };
    // Simulate async operation
    await new Promise(resolve => setTimeout(resolve, 500));
    return explanations[topic] || `${topic}: ${context}`;
}

const PendleModule: React.FC = () => {
    const [state, setState] = useState<TokenState>(TokenState.Underlying);
    const [timeProgress, setTimeProgress] = useState(0); // 0 to 100
    const [aiExplanation, setAiExplanation] = useState<{ loading: boolean; text: string | null }>({
        loading: false,
        text: null,
    });

    const principalAmount = 1000;
    const fixedApy = 12; // 12% Fixed Rate (Market Consensus at t=0)

    // Generate deterministic simulation data for variable rates
    // Start around 12% to match the fixed pricing
    const [simData] = useState(() => {
        const rates: number[] = [];
        const accumulated: number[] = [0];
        let currentRate = 12.0;
        const steps = 100;

        // Generate 101 points (0 to 100)
        for (let i = 0; i <= steps; i++) {
            rates.push(currentRate);

            // Calculate yield for this step (1/100th of a year)
            if (i > 0) {
                const stepYield = principalAmount * (rates[i - 1] / 100) * (1 / 100);
                accumulated.push(accumulated[i - 1] + stepYield);
            }

            // Random walk for next rate
            const change = (Math.random() - 0.5) * 4; // Volatility
            currentRate += change;
            // Clamp rate between 2% and 40%
            currentRate = Math.max(2, Math.min(40, currentRate));
        }
        return { rates, accumulated };
    });

    // Derived values based on time progress
    const currentVariableApy = simData.rates[timeProgress];
    const currentYield = simData.accumulated[timeProgress];

    // REALISTIC PRICING MODEL: Asset = PT + YT
    // 1. PT Price = Principal / (1 + Rate)^Time
    // At t=0 (1 year to maturity), PT = 1000 / 1.12
    const startPtValue = principalAmount / (1 + fixedApy / 100); // ~892.86
    const ptValue = startPtValue + ((principalAmount - startPtValue) * (timeProgress / 100));

    // PT Yield Calculation (Fixed)
    const ptAccrued = ptValue - startPtValue;
    const ptYieldPercent = (ptAccrued / startPtValue) * 100;

    // 2. YT Price = Asset - PT
    // At t=0, YT = 1000 - 892.86 = ~107.14
    // YT decays to 0 at maturity
    const startYtValue = principalAmount - startPtValue;
    const ytValue = startYtValue * (1 - timeProgress / 100);

    // YT PnL Calculation
    const ytCost = startYtValue;
    const ytTotalValue = ytValue + currentYield;
    const ytPnL = ytTotalValue - ytCost;

    // Realized APY Calculation
    let ytRealizedApy = 0;
    if (timeProgress > 0) {
        // APY based on Capital Efficiency
        // (Profit / Cost) * (1 / Years)
        const roi = ytPnL / ytCost;
        const yearsElapsed = timeProgress / 100;
        ytRealizedApy = (roi / yearsElapsed) * 100;
    }

    // Days left calculation
    const daysLeft = Math.ceil(365 * (1 - timeProgress / 100));

    const handleExplain = async (topic: string) => {
        setAiExplanation({ loading: true, text: null });
        let context = "";
        if (topic === "Underlying") context = "The user is looking at the raw asset (e.g., stETH) before interacting with Pendle.";
        if (topic === "SY") context = "The asset has been wrapped into Standardized Yield (SY) tokens to be compatible with the Pendle AMM.";
        if (topic === "PT") context = "The token has been split. User sees PT (Principal Token) which represents the principal amount redeemable at maturity.";
        if (topic === "YT") context = "The token has been split. User sees YT (Yield Token) which represents the claim on all future yield.";

        const explanation = await explainPendleConcept(topic, context);
        setAiExplanation({ loading: false, text: explanation });
    };

    const reset = () => {
        setState(TokenState.Underlying);
        setTimeProgress(0);
        setAiExplanation({ loading: false, text: null });
    };

    // Helper for Stepper styling
    const stepClass = (target: TokenState) => {
        const isActive = state === target;
        return `px-6 py-2 rounded-full text-xs font-bold transition-all ${isActive
            ? 'bg-slate-800 text-white border border-slate-700'
            : 'text-slate-500 hover:text-slate-300 hover:bg-slate-800/50'
            }`;
    };

    return (
        <div className="w-full min-h-[720px] bg-slate-900 rounded-2xl overflow-hidden flex flex-col relative">
            {/* Header */}
            <div className="bg-slate-950 p-6 flex justify-center items-center">

                {/* Centered Stepper */}
                <div className="bg-slate-900 p-1 rounded-full border border-slate-800 flex gap-1">
                    <button onClick={() => setState(TokenState.Underlying)} className={stepClass(TokenState.Underlying)}>1. ASSET</button>
                    <button onClick={() => setState(TokenState.SY)} className={stepClass(TokenState.SY)}>2. WRAP (SY)</button>
                    <button onClick={() => setState(TokenState.Split)} className={stepClass(TokenState.Split)}>3. SPLIT (PT/YT)</button>
                </div>

            </div>

            {/* Main Interactive Area */}
            <div className="p-10 flex-1 flex flex-col items-center justify-center relative bg-gradient-to-b from-slate-900 to-slate-950">

                <AnimatePresence mode="wait">

                    {/* STATE 1: UNDERLYING */}
                    {state === TokenState.Underlying && (
                        <motion.div
                            key="underlying"
                            initial={{ opacity: 0, scale: 0.95 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={{ opacity: 0 }}
                            className="flex flex-col items-center gap-8 py-10"
                        >
                            <div className="relative group cursor-help mb-8" onClick={() => handleExplain("Underlying Asset")}>
                                <div className="w-48 h-48 rounded-full bg-slate-800/50 border-4 border-slate-700 flex items-center justify-center shadow-lg transition-all overflow-hidden p-8">
                                    <Image src={stEthImg} alt="stETH" className="w-full h-full object-contain" />
                                </div>
                                <div className="absolute -bottom-16 left-1/2 -translate-x-1/2 whitespace-nowrap text-center">
                                    <p className="text-2xl font-bold text-slate-200">1 stETH</p>
                                    <p className="text-sm text-slate-500">Yield Bearing Asset</p>
                                </div>
                            </div>

                            <div className="mt-8 text-center max-w-md text-slate-400 text-lg">
                                Start with a yield-bearing asset. <br />It generates generic yield over time.
                            </div>

                            <button
                                onClick={() => setState(TokenState.SY)}
                                className="mt-4 px-8 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-white rounded-xl flex items-center gap-2 transition-all font-bold text-lg"
                            >
                                Standardize <ArrowRight className="w-5 h-5" />
                            </button>
                        </motion.div>
                    )}

                    {/* STATE 2: SY TOKEN */}
                    {state === TokenState.SY && (
                        <motion.div
                            key="sy"
                            initial={{ opacity: 0, scale: 0.95 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={{ opacity: 0 }}
                            className="flex flex-col items-center gap-8 py-10"
                        >
                            <div className="relative cursor-help mb-8" onClick={() => handleExplain("Standardized Yield (SY)")}>
                                <div className="w-48 h-48 rounded-3xl bg-slate-800/50 border-4 border-slate-700 flex items-center justify-center shadow-lg rotate-45 transform transition-all group-hover:rotate-90 overflow-hidden p-8">
                                    <div className="-rotate-45 w-full h-full flex items-center justify-center">
                                        <Image src={stEthImg} alt="SY-stETH" className="w-full h-full object-contain" />
                                    </div>
                                </div>
                                <div className="absolute -bottom-20 left-1/2 -translate-x-1/2 whitespace-nowrap text-center">
                                    <p className="text-2xl font-bold text-slate-200">SY-stETH</p>
                                    <p className="text-sm text-slate-500">Standardized Yield</p>
                                </div>
                            </div>

                            <div className="mt-12 text-center max-w-md text-slate-400 text-lg">
                                The asset is wrapped into <strong>SY</strong> (Standardized Yield) to communicate with the Pendle protocol.
                            </div>

                            <div className="flex gap-6 mt-4">
                                <button
                                    onClick={() => setState(TokenState.Underlying)}
                                    className="px-6 py-3 text-slate-400 hover:text-white text-sm font-medium"
                                >
                                    Back
                                </button>
                                <button
                                    onClick={() => setState(TokenState.Split)}
                                    className="px-8 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-white rounded-xl flex items-center gap-2 transition-all font-bold text-lg"
                                >
                                    Tokenize Yield <Split className="w-5 h-5" />
                                </button>
                            </div>
                        </motion.div>
                    )}

                    {/* STATE 3: SPLIT (PT & YT) */}
                    {state === TokenState.Split && (
                        <motion.div
                            key="split"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            className="w-full flex flex-col items-center gap-6"
                        >
                            {/* Top Section: Charts and Controls */}
                            <div className="w-full grid grid-cols-1 lg:grid-cols-3 gap-6">

                                {/* Rate Flow Visualization */}
                                <div className="lg:col-span-2 bg-slate-900/50 rounded-2xl p-6 border border-slate-800 relative overflow-hidden flex flex-col justify-end min-h-[180px]">
                                    <div className="flex justify-between items-start mb-4 absolute top-6 left-6 right-6 z-10">
                                        <span className="text-xs font-bold text-slate-400 flex items-center gap-2">
                                            <Activity className="w-4 h-4 text-emerald-400" /> VARIABLE RATE SIMULATION
                                        </span>
                                        <div className="flex flex-col items-end">
                                            <span className="text-2xl font-mono text-white font-bold tracking-tight">
                                                {currentVariableApy.toFixed(2)}%
                                            </span>
                                            <span className="text-[10px] text-slate-500 uppercase tracking-wider">Current APY</span>
                                        </div>
                                    </div>
                                    {/* Bars */}
                                    <div className="flex items-end h-24 gap-[4px] w-full opacity-90">
                                        {simData.rates.map((r, i) => (
                                            <div
                                                key={i}
                                                className={`flex-1 rounded-t-sm transition-colors duration-100 ${i <= timeProgress ? 'bg-emerald-500' : 'bg-slate-700/20'}`}
                                                style={{ height: `${(r / 40) * 100}%` }}
                                            ></div>
                                        ))}
                                    </div>
                                </div>

                                {/* Simulation Controls */}
                                <div className="bg-slate-800/40 p-6 rounded-2xl border border-slate-700/50 flex flex-col justify-center">
                                    <div className="flex justify-between items-end mb-4">
                                        <label className="text-xs font-bold text-slate-400 flex items-center gap-2">
                                            <Clock className="w-4 h-4" /> TIME TRAVEL
                                        </label>
                                        <span className="text-sm text-indigo-400 font-mono font-bold">
                                            {daysLeft} DAYS LEFT
                                        </span>
                                    </div>
                                    <input
                                        type="range"
                                        min="0"
                                        max="100"
                                        value={timeProgress}
                                        onChange={(e) => setTimeProgress(parseInt(e.target.value))}
                                        className="w-full h-3 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-emerald-500"
                                    />
                                    <div className="flex justify-between text-[10px] text-slate-500 mt-2 font-mono tracking-wider">
                                        <span>TODAY</span>
                                        <span>MATURITY</span>
                                    </div>

                                    <button
                                        onClick={reset}
                                        className="mt-6 w-full py-2 text-slate-400 hover:text-white text-xs border border-slate-700/50 rounded-lg hover:border-slate-500 hover:bg-slate-800 transition-all"
                                    >
                                        Reset Simulation
                                    </button>
                                </div>

                            </div>

                            {/* Bottom Section: Cards */}
                            <div className="w-full grid grid-cols-2 gap-8 mt-4">

                                {/* PT CARD */}
                                <motion.div
                                    className="bg-slate-800/40 border border-slate-700 p-6 rounded-2xl flex flex-col hover:border-indigo-500/50 transition-colors cursor-pointer relative overflow-hidden group min-h-[280px]"
                                    onClick={() => handleExplain("PT (Principal Token)")}
                                    whileHover={{ scale: 1.01 }}
                                >
                                    {/* Progress Bar Top */}
                                    <div className="absolute top-0 left-0 w-full h-1.5 bg-slate-700">
                                        <div className="h-full bg-indigo-500 transition-all duration-300" style={{ width: `${(ptValue / principalAmount) * 100}%` }}></div>
                                    </div>

                                    <div className="flex items-start justify-between mb-6">
                                        <div>
                                            <div className="flex items-center gap-3 mb-1">
                                                <div className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center border border-slate-700">
                                                    <span className="font-bold text-white text-sm">PT</span>
                                                </div>
                                                <h3 className="text-xl font-bold text-slate-200">Principal Token</h3>
                                            </div>
                                            <p className="text-xs text-slate-400">Redeemable for principal at maturity</p>
                                        </div>
                                        <Info className="w-5 h-5 text-slate-600 opacity-0 group-hover:opacity-100 transition-opacity" />
                                    </div>

                                    <div className="space-y-4 flex-1">
                                        <div className="flex justify-between items-baseline border-b border-slate-700/50 pb-2">
                                            <span className="text-sm text-slate-500 font-medium">Current Value</span>
                                            <span className="text-2xl text-white font-mono font-medium">${ptValue.toFixed(2)}</span>
                                        </div>
                                        <div className="flex justify-between items-baseline pb-2">
                                            <span className="text-sm text-slate-500 font-medium">Fixed Yield</span>
                                            <div className="text-right">
                                                <span className="text-xl text-green-400 font-mono font-medium block">+${ptAccrued.toFixed(2)}</span>
                                                <span className="text-xs text-green-500/70 block">{ptYieldPercent.toFixed(2)}% Return</span>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="mt-4 text-xs text-center text-slate-500 bg-slate-900/30 py-2 rounded-lg border border-slate-800/50">
                                        Locked Fixed APY: <span className="text-slate-300">{fixedApy}%</span> • Target: <span className="text-slate-300">${principalAmount}</span>
                                    </div>
                                </motion.div>

                                {/* YT CARD */}
                                <motion.div
                                    className="bg-slate-800/40 border border-slate-700 p-6 rounded-2xl flex flex-col hover:border-emerald-500/50 transition-colors cursor-pointer relative overflow-hidden group min-h-[280px]"
                                    onClick={() => handleExplain("YT (Yield Token)")}
                                    whileHover={{ scale: 1.01 }}
                                >
                                    {/* Progress Bar Top */}
                                    <div className="absolute top-0 left-0 w-full h-1.5 bg-slate-700">
                                        <div className="h-full bg-emerald-500 transition-all duration-300" style={{ width: `${(1 - timeProgress / 100) * 100}%` }}></div>
                                    </div>

                                    <div className="flex items-start justify-between mb-6">
                                        <div>
                                            <div className="flex items-center gap-3 mb-1">
                                                <div className="p-2 rounded-lg bg-slate-800 border border-slate-700">
                                                    <span className="font-bold text-emerald-400">YT</span>
                                                </div>
                                                <h3 className="text-xl font-bold text-slate-200">Yield Token</h3>
                                            </div>
                                            <p className="text-xs text-slate-400">Claim on all future yield</p>
                                        </div>
                                        <Info className="w-5 h-5 text-slate-600 opacity-0 group-hover:opacity-100 transition-opacity" />
                                    </div>

                                    <div className="space-y-4 flex-1">
                                        <div className="flex justify-between items-baseline border-b border-slate-700/50 pb-2">
                                            <span className="text-sm text-slate-500 font-medium">Token Value</span>
                                            <span className="text-2xl text-white font-mono font-medium">${ytValue.toFixed(2)}</span>
                                        </div>
                                        <div className="flex justify-between items-baseline border-b border-slate-700/50 pb-2">
                                            <span className="text-sm text-slate-500 font-medium">Yield Collected</span>
                                            <span className="text-xl text-green-400 font-mono font-medium">+${currentYield.toFixed(2)}</span>
                                        </div>
                                        <div className="flex justify-between items-baseline">
                                            <span className="text-sm text-slate-500 font-medium">Net PnL (Cost ${ytCost.toFixed(0)})</span>
                                            <div className="text-right">
                                                <span className={`text-xl font-mono font-medium block ${ytPnL >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                                                    {ytPnL >= 0 ? '+' : ''}${ytPnL.toFixed(2)}
                                                </span>
                                                <span className={`text-xs block ${ytPnL >= 0 ? 'text-green-500/70' : 'text-red-500/70'}`}>
                                                    Realized APY: {Math.abs(ytRealizedApy).toFixed(1)}%
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="mt-4 text-xs text-center text-slate-500 bg-slate-900/30 py-2 rounded-lg border border-slate-800/50">
                                        Decays to $0 • Profitable if Avg APY &gt; {fixedApy}%
                                    </div>
                                </motion.div>

                            </div>

                        </motion.div>
                    )}
                </AnimatePresence>
            </div>

        </div>
    );
};

export default PendleModule;
